<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ContactInformation;
use App\Models\Education;
use App\Models\Experience;
use App\Models\Interests;
use App\Models\Languages;
use App\Models\PersonalInformation;
use App\Models\Projects;
use App\Models\Skills;
use App\Helpers\Tokenizer;
use App\Helpers\Stopwords;
use App\Helpers\Stemming;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Collection;

class NLPController extends Controller
{
    private $jobPostings; // Declare the instance variable

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Get the authenticated user's ID
        $userId = auth()->id();

        // Fetch the data for the authenticated user
        $personal_information = PersonalInformation::where('user_id', $userId)->get()->toArray();

        $id = $personal_information[0]['id'];
        $contact_information = ContactInformation::where('user_id', $id)->get()->toArray();
        $education = Education::where('user_id', $id)->get()->toArray();
        $experience = Experience::where('user_id', $id)->get()->toArray();
        $interests = Interests::where('user_id', $id)->get()->toArray();
        $languages = Languages::where('user_id', $id)->get()->toArray();
        $projects = Projects::where('user_id', $id)->get()->toArray();
        $skills = Skills::where('user_id', $id)->get()->toArray();

        $degreeTitle = $education[0]['degree_title'];
        $response = Http::get("http://localhost:5000/keyword/{$degreeTitle}/location/Beirut");
        $body = json_decode($response->body());
        $url = $body->url;

        $getBody = Http::get($url);
        $bodyjson = json_decode($getBody->body());

        if ($bodyjson !== null && isset($bodyjson->jobPostings)) {
            $this->jobPostings = array_slice($bodyjson->jobPostings, 0, 60);

            // Preprocessing
            $tokenizer = new Tokenizer();
            $stopwords = new Stopwords();
            $stemmer = new Stemming();

            // Terms of interest
            $terms = [
    "doctor",
    "dentist",
    "nurse",
    "pharmacist",
    "surgeon",
    "physician",
    "veterinarian",
    "psychologist",
    "therapist",
    "optometrist",
    "radiologist",
    "pathologist",
    "audiologist",
    "paramedic",
    "anesthesiologist",
    "dermatologist",
    "orthodontist",
    "pediatrician",
    "chiropractor",
    "oncologist",
    "cardiologist",
    "gynecologist",
    "neurologist",
    "endocrinologist",
    "urologist",
    "obstetrician",
    "ophthalmologist",
    "gastroenterologist",
    "internist",
    "allergist",
    "immunologist",
    "hematologist",
    "family physician",
    "general practitioner",
    "diagnostician",
    "geriatrician",
    "neonatologist",
    "toxicologist",
    "epidemiologist",
    "forensic pathologist",
    "phlebotomist",
    "biochemist",
    "biologist",
    "chemist",
    "microbiologist",
    "geneticist",
    "physiologist",
    "zoologist",
    "botanist",
    "ecologist",
    "virologist",
    "immunologist",
    "parasitologist",
    "biotechnologist",
    "forensic scientist",
    "toxicologist",
    "pharmacologist",
    "epidemiologist",
    "medical researcher",
    "biomedical engineer",
    "bioinformatician",
    "health informatician",
    "medical illustrator",
    "hospital administrator",
    "medical writer",
    "medical sales representative",
    "medical device technician",
    "dental hygienist",
    "dental assistant",
    "orthodontic technician",
    "prosthodontist",
    "dental laboratory technician",
    "dental ceramist",
    "dental office manager",
    "periodontist",
    "endodontist",
    "dental therapist",
    "dental receptionist",
    "dental consultant",
    "registered nurse",
    "licensed practical nurse",
    "nursing assistant",
    "nurse practitioner",
    "clinical nurse specialist",
    "nurse anesthetist",
    "nurse midwife",
    "pediatric nurse",
    "geriatric nurse",
    "psychiatric nurse",
    "neonatal nurse",
    "critical care nurse",
    "emergency nurse",
    "surgical nurse",
    "obstetric nurse",
    "oncology nurse",
    "orthopedic nurse",
    "public health nurse",
    "school nurse",
    "occupational health nurse",
    "travel nurse",
    "nursing informatics specialist",
    "nurse educator",
    "nurse researcher",
    "pharmacist",
    "pharmacy technician",
    "clinical pharmacist",
    "hospital pharmacist",
    "retail pharmacist",
    "industrial pharmacist",
    "nuclear pharmacist",
    "compounding pharmacist",
    "pharmacy manager",
    "pharmacy sales representative",
    "pharmaceutical researcher",
    "pharmacy informatician",
    "pharmaceutical technician",
    "clinical psychologist",
    "counseling psychologist",
    "school psychologist",
    "industrial-organizational psychologist",
    "forensic psychologist",
    "neuropsychologist",
    "health psychologist",
    "sports psychologist",
    "research psychologist",
    "educational psychologist",
    "developmental psychologist",
    "rehabilitation psychologist",
    "clinical therapist",
    "mental health counselor",
    "marriage and family therapist",
    "substance abuse counselor",
    "art therapist",
    "music therapist",
    "play therapist",
    "occupational therapist",
    "physical therapist",
    "respiratory therapist",
    "speech-language pathologist",
    "audiologist",
    "optometrist",
    "ophthalmologist",
    "radiologist",
    "ultrasound technician",
    "medical laboratory technologist",
    "phlebotomist",
    "medical coder",
    "medical billing specialist",
    "medical transcriptionist",
    "medical illustrator",
    "medical scribe",
    "healthcare administrator",
    "health information manager",
    "healthcare consultant",
    "hospital CEO",
    "medical librarian",
    "healthcare marketing specialist",
    "medical sales representative",
    "medical device technician",
    "epidemiologist",
    "biostatistician",
    "public health specialist",
    "health educator",
    "community health worker",
    "nutritionist",
    "dietitian",
    "health coach",
    "fitness trainer",
    "yoga instructor",
    "massage therapist",
    "personal trainer",
    "sports coach",
    "physical education teacher",
    "athletic trainer",
    "nutritionist",
    "dietitian",
    "food scientist",
    "culinary chef",
    "sous chef",
    "pastry chef",
    "sommelier",
    "food critic",
    "caterer",
    "restaurant manager",
    "hotel manager",
    "event planner",
    "marketing manager",
    "sales manager",
    "business analyst",
    "financial analyst",
    "data analyst",
    "market researcher",
    "investment banker",
    "stockbroker",
    "accountant",
    "auditor",
    "tax consultant",
    "financial advisor",
    "economist",
    "actuary",
    "budget analyst",
    "management consultant",
    "human resources manager",
    "recruiter",
    "public relations specialist",
    "advertising executive",
    "copywriter",
    "graphic designer",
    "web designer",
    "UI/UX designer",
    "motion graphics designer",
    "videographer",
    "photographer",
    "art director",
    "creative director",
    "copy editor",
    "proofreader",
    "content writer",
    "journalist",
    "technical writer",
    "translator",
    "interpreter",
    "scriptwriter",
    "novelist",
    "poet",
    "playwright",
    "screenwriter",
    "editor",
    "literary agent",
    "book publisher",
    "publishing assistant",
    "bookstore owner",
    "research scientist",
    "data scientist",
    "computer scientist",
    "biomedical scientist",
    "environmental scientist",
    "forensic scientist",
    "chemists",
    "physicist",
    "astronomer",
    "geologist",
    "oceanographer",
    "mathematician",
    "statistician",
    "research assistant",
    "laboratory technician",
    "field technician",
    "science writer",
    "science illustrator",
    "science educator",
    "analytical chemist",
    "organic chemist",
    "inorganic chemist",
    "physical chemist",
    "biochemist",
    "forensic chemist",
    "pharmaceutical chemist",
    "agricultural scientist",
    "environmental scientist",
    "wildlife biologist",
    "marine biologist",
    "conservationist",
    "ecologist",
    "botanist",
    "zoologist",
    "ornithologist",
    "herpetologist",
    "entomologist",
    "veterinarian",
    "animal behaviorist",
    "animal trainer",
    "pet groomer",
    "zookeeper",
    "wildlife rehabilitator",
    "animal control officer",
    "veterinary technician",
    "veterinary assistant",
    "animal nutritionist",
    "animal geneticist",
    "animal shelter manager",
    "animal rights activist",
    "fashion designer",
    "graphic designer",
    "interior designer",
    "industrial designer",
    "jewelry designer",
    "product designer",
    "textile designer",
    "costume designer",
    "furniture designer",
    "automotive designer",
    "architect",
    "landscape architect",
    "urban planner",
    "civil engineer",
    "mechanical engineer",
    "electrical engineer",
    "chemical engineer",
    "computer engineer",
    "aerospace engineer",
    "biomedical engineer",
    "environmental engineer",
    "structural engineer",
    "nuclear engineer",
    "geotechnical engineer",
    "transportation engineer",
    "water resources engineer",
    "robotics engineer",
    "petroleum engineer",
    "sound engineer",
    "systems engineer",
    "software engineer",
    "web developer",
    "mobile app developer",
    "game developer",
    "database administrator",
    "network administrator",
    "IT manager",
    "computer programmer",
    "cybersecurity analyst",
    "data analyst",
    "data scientist",
    "machine learning engineer",
    "artificial intelligence specialist",
    "systems analyst",
    "UI/UX designer",
    "frontend developer",
    "backend developer",
    "full-stack developer",
    "QA tester",
    "technical support specialist",
    "IT consultant",
    "IT trainer",
    "network engineer",
    "cloud architect",
    "digital marketer",
    "social media manager",
    "SEO specialist",
    "content strategist",
    "email marketer",
    "web analyst",
    "online advertising specialist",
    "brand manager",
    "market researcher",
    "media buyer",
    "public relations specialist",
    "event planner",
    "sales manager",
    "business development manager",
    "account manager",
    "customer success manager",
    "project manager",
    "operations manager",
    "supply chain manager",
    "logistics manager",
    "quality assurance manager",
    "human resources manager",
    "training and development manager",
    "finance manager",
    "investment banker",
    "financial advisor",
    "financial analyst",
    "wealth manager",
    "insurance agent",
    "actuary",
    "tax consultant",
    "budget analyst",
    "real estate agent",
    "property manager",
    "mortgage broker",
    "loan officer",
    "credit analyst",
    "stockbroker",
    "investment analyst",
    "risk manager",
    "management consultant",
    "business analyst",
    "business intelligence analyst",
    "data analyst",
    "marketing analyst",
    "operations analyst",
    "strategy consultant",
    "supply chain analyst",
    "financial consultant",
    "project coordinator",
    "executive assistant",
    "administrative assistant",
    "office manager",
    "virtual assistant",
    "data entry specialist",
    "receptionist",
    "customer service representative",
    "call center agent",
    "sales representative",
    "account executive",
    "retail associate",
    "cashier",
    "store manager",
    "buyer",
    "merchandiser",
    "supply chain coordinator",
    "warehouse manager",
    "logistics coordinator",
    "production supervisor",
    "operations coordinator",
    "quality control inspector",
    "research and development scientist",
    "product manager",
    "product marketing manager",
    "brand strategist",
    "UX researcher",
    "user interface designer",
    "growth hacker",
    "content writer",
    "social media strategist",
    "digital strategist",
    "e-commerce manager",
    "customer success manager",
    "sales manager",
    "business development manager",
    "account manager",
    "public relations manager",
    "event coordinator",
    "marketing coordinator",
    "data analyst",
    "business analyst",
    "financial analyst",
    "market researcher",
    "project manager",
    "operations manager",
    "human resources manager",
    "training and development manager",
    "finance manager",
    "investment banker",
    "financial advisor",
    "wealth manager",
    "insurance agent",
    "actuary",
    "tax consultant",
    "budget analyst",
    "real estate agent",
    "property manager",
    "mortgage broker",
    "loan officer",
    "credit analyst",
    "stockbroker",
    "investment analyst",
    "risk manager",
    "management consultant",
    "business analyst",
    "business intelligence analyst",
    "data analyst",
    "marketing analyst",
    "operations analyst",
    "strategy consultant",
    "supply chain analyst",
    "financial consultant",
    "project coordinator",
    "executive assistant",
    "administrative assistant",
    "office manager",
    "virtual assistant",
    "data entry specialist",
    "receptionist",
    "customer service representative",
    "call center agent",
    "sales representative",
    "account executive",
    "retail associate",
    "cashier",
    "store manager",
    "buyer",
    "merchandiser",
    "supply chain coordinator",
    "warehouse manager",
    "logistics coordinator",
    "production supervisor",
    "operations coordinator",
    "quality control inspector",
    "research and development scientist",
    "product manager",
    "product marketing manager",
    "brand strategist",
    "UX researcher",
    "user interface designer",
    "growth hacker",
    "content writer",
    "social media strategist",
    "digital strategist",
    "e-commerce manager",
    "customer success manager",
    "sales manager",
    "business development manager",
    "account manager",
    "public relations manager",
    "event coordinator",
    "marketing coordinator",
    "data analyst",
    "business analyst",
    "financial analyst",
    "market researcher",
    "project manager",
    "operations manager",
    "human resources manager",
    "training and development manager",
    "finance manager",
    "investment banker",
    "financial advisor",
    "wealth manager",
    "insurance agent",
    "actuary",
    "tax consultant",
    "budget analyst",
    "real estate agent",
    "property manager",
    "mortgage broker",
    "loan officer",
    "credit analyst",
    "stockbroker",
    "investment analyst",
    "risk manager",
    "management consultant",
    "business analyst",
    "business intelligence analyst",
    "data analyst",
    "marketing analyst",
    "operations analyst",
    "strategy consultant",
    "supply chain analyst",
    "financial consultant",
    "project coordinator",
    "executive assistant",
    "administrative assistant",
    "office manager",
    "virtual assistant",
    "data entry specialist",
    "receptionist",
    "customer service representative",
    "call center agent",
    "sales representative",
    "account executive",
    "retail associate",
    "cashier",
    "store manager",
    "buyer",
    "merchandiser",
    "supply chain coordinator",
    "warehouse manager",
    "logistics coordinator",
    "production supervisor",
    "operations coordinator",
    "quality control inspector",
    "research and development scientist",
    "product manager",
    "product marketing manager",
    "brand strategist",
    "UX researcher",
    "user interface designer",
    "growth hacker",
    "content writer",
    "social media strategist",
    "digital strategist",
    "e-commerce manager",
    "customer success manager",
    "sales manager",
    "business development manager",
    "account manager",
    "public relations manager",
    "event coordinator",
    "marketing coordinator",
    "data analyst",
    "business analyst",
    "financial analyst",
    "market researcher",
    "project manager",
    "operations manager",
    "human resources manager",
    "training and development manager",
    "finance manager",
    "investment banker",
    "financial advisor",
    "wealth manager",
    "insurance agent",
    "actuary",
    "tax consultant",
    "budget analyst",
    "real estate agent",
    "property manager",
    "mortgage broker",
    "loan officer",
    "credit analyst",
    "stockbroker",
    "investment analyst",
    "risk manager",
    "management consultant",
    "business analyst",
    "business intelligence analyst",
    "data analyst",
    "marketing analyst",
    "operations analyst",
    "strategy consultant",
    "supply chain analyst",
    "financial consultant",
    "project coordinator",
    "executive assistant",
    "administrative assistant",
    "office manager",
    "virtual assistant",
    "data entry specialist",
    "receptionist",
    "customer service representative",
    "call center agent",
    "sales representative",
    "account executive",
    "retail associate",
    "cashier",
    "store manager",
    "buyer",
    "merchandiser",
    "supply chain coordinator",
    "warehouse manager",
    "logistics coordinator",
    "production supervisor",
    "operations coordinator",
    "quality control inspector",
    "research and development scientist",
    "product manager",
    "product marketing manager",
    "brand strategist",
    "UX researcher",
    "user interface designer",
    "growth hacker",
    "content writer",
    "social media strategist",
    "digital strategist",
    "e-commerce manager",
    "customer success manager",
    "sales manager",
    "business development manager",
    "account manager",
    "public relations manager",
    "event coordinator",
    "marketing coordinator",
    "data analyst",
    "business analyst",
    "financial analyst",
    "market researcher",
    "project manager",
    "operations manager",
    "human resources manager",
    "training and development manager",
    "finance manager",
    "investment banker",
    "financial advisor",
    "wealth manager",
    "insurance agent",
    "actuary",
    "tax consultant",
    "budget analyst",
    "real estate agent",
    "property manager",
    "mortgage broker",
    "loan officer",
    "credit analyst",
    "stockbroker",
    "investment analyst",
    "risk manager",
    "management consultant",
    "business analyst",
    "business intelligence analyst",
    "data analyst",
    "marketing analyst",
    "operations analyst",
    "strategy consultant",
    "supply chain analyst",
    "financial consultant",
    "project coordinator",
    "executive assistant"];

            // Calculate TF-IDF for each term
            $totalDocuments = count($this->jobPostings);
            $documentFrequency = array_fill_keys($terms, 0);

            $jobPostingsWithTFIDF = new Collection();

            foreach ($this->jobPostings as $jobPosting) {
                $text = $jobPosting->title . ' ' . $jobPosting->location . ' ' . $jobPosting->url;

                // Tokenize the text into individual terms
                $terms = $tokenizer->tokenize($text);

                // Remove stopwords and perform stemming on the terms
                $terms = $stopwords->removeStopwords($terms);
                $terms = $stemmer->stem($terms);

                            // Calculate term frequency for each term
            $termFrequencies = array_fill_keys($terms, 0);
            foreach ($terms as $term) {
                if (isset($termFrequencies[$term])) {
                    $termFrequencies[$term]++;
                }
            }

            // Update document frequency for each term
            foreach ($terms as $term) {
                if (isset($documentFrequency[$term]) && $termFrequencies[$term] > 0) {
                    $documentFrequency[$term]++;
                }
            }

                // Calculate TF-IDF for each term
                $tfidfScores = [];
                foreach ($terms as $term) {
                    $tf = $termFrequencies[$term] / count($terms);

                    $tfidf = $tf ;
                    $tfidfScores[$term] = $tfidf;
                }


                // Store the job posting with its TF-IDF scores
                $jobPostingsWithTFIDF->push([
                    'jobPosting' => $jobPosting,
                    'tfidfScores' => $tfidfScores
                ]);
            }

            // Sort the job postings by the highest TF-IDF score for each term
            $sortedJobPostings = $jobPostingsWithTFIDF->sortByDesc(function ($item) use ($terms) {
                $tfidfScores = $item['tfidfScores'];
                $maxTFIDF = 0;

                foreach ($terms as $term) {
                    if (isset($tfidfScores[$term]) && $tfidfScores[$term] > $maxTFIDF) {
                        $maxTFIDF = $tfidfScores[$term];
                    }
                }

                return $maxTFIDF;
            });

            return view('jobspage.index', compact('sortedJobPostings'));
        } else {
            echo "No job postings found.";
        }
        session(['bodyJson' => $bodyjson]);
    }
}
